### PR TITLE
Added SortInWaveForm.cpp

### PR DESCRIPTION
**Pull request by ashish5433**
Pls review my pr @MohammedHamzaMalik .Do inform me if you need any changes.

### CODE REVIEW

**Review by MohammedHamzaMalik — CHANGES_REQUESTED** [review]
Add the solution to the specific topic folder within the particular course folder.

**Comment by ashish5433** [comment]
> Add the solution to the specific topic folder within the particular course folder.

Hii @MohammedHamzaMalik , do i have to make a new folder? Pls tell

**Comment by MohammedHamzaMalik** [comment]
> > Add the solution to the specific topic folder within the particular course folder.
> 
> Hii @MohammedHamzaMalik , do i have to make a new folder? Pls tell

Yes, if the folder doesn't exist.

**Comment by ashish5433** [comment]
I have changed file directory as you instructed @MohammedHamzaMalik

**Review by MohammedHamzaMalik — APPROVED** [review]
Ok

**Pull request merged**
