### PR TITLE
Added STL

### PR DESCRIPTION
**Pull request by DevasisPanda**

### CODE REVIEW

**Review by MohammedHamzaMalik — CHANGES_REQUESTED** [review]
Add an explanation of the problem before adding the code.

For reference check out the existing files.

**Comment by DevasisPanda** [comment]
As I have added the information On essential STL files used in programming.
Do you want me to add a markdown file explaining it ??
Sorry I couldn't find any reference in this repo.

**Review by MohammedHamzaMalik — COMMENTED** [review]
Ok, no problem.

**Review by MohammedHamzaMalik — APPROVED** [review]
I will merge this PR.

**Pull request merged**
